ARG BASE_IMAGE_TAG
FROM austincloud/terratest:$BASE_IMAGE_TAG

# These args are set by the base image and shall not be 
# modified save a drastic change.
ARG BASE_IMAGE_USERNAME=terratest
ARG USERNAME=terraform
ARG ROOT_PASS
ARG GROUP=terratest
ARG HOME=/home/$USERNAME
ARG ADDITIONAL_APT_PACKAGES
ARG ADDITIONAL_PROVISIONING_SCRIPT
ARG YQ_VERSION="v4.28.1"
ARG NVIM_VERSION="v0.8.3"
ARG GO_VERSION="1.20.6"

ARG ELAM_ABSPATH="$HOME/elam"

USER root

RUN usermod -l $USERNAME $BASE_IMAGE_USERNAME
RUN usermod -m -d $HOME $USERNAME
RUN echo "root:$ROOT_PASS" | chpasswd

RUN apt update && apt install -y \
  jq \
  less \
  zip \
  $ADDITIONAL_APT_PACKAGES
  # git-crypt \

RUN wget "https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz" && \
   rm -rf /usr/local/go && \
   tar -C /usr/local -xzf "go$GO_VERSION.linux-amd64.tar.gz"

# Yq requires manual retrieval of the package
RUN wget \
  https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64 \
  -O /usr/bin/yq && \
  chmod +x /usr/bin/yq

# Neovim requires manual retrieval of the latest version
# as the apt package and devcontainer feature is quite old
RUN wget https://github.com/neovim/neovim/releases/download/$NVIM_VERSION/nvim-linux64.deb \
  -O /neovim.deb
RUN apt install -y /neovim.deb 
RUN rm /neovim.deb
ENV EDITOR=nvim

# Elam
RUN git clone https://github.com/utkusarioglu/elam.git $ELAM_ABSPATH

# hclq is not available in devcontainer features
RUN curl -sSLo install.sh https://install.hclq.sh && \
  sh install.sh && \
  rm install.sh

# infracost
RUN curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
RUN mkdir -p $HOME/.config/infracost && \
  chown -R $USERNAME:$GROUP $HOME/.config/infracost

COPY $ADDITIONAL_PROVISIONING_SCRIPT /scripts/provisioning.sh
RUN if [ -f /scripts/provisioning.sh ]; then /scripts/provisioning.sh; fi

USER $USERNAME
RUN mkdir -p $HOME/.vscode-server/extensions
RUN mkdir -p $HOME/.vscode-server-insiders/extensions

# Gists
ADD --chown=${USERNAME}:${GROUP} \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/create-env-example.sh \
  /scripts/create-env-example.sh
ADD --chown=${USERNAME}:${GROUP} \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/.bashrc \
  $HOME/.bashrc
ADD --chown=${USERNAME}:${GROUP} \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/.inputrc \
  $HOME/.inputrc

# This makes elam easier to use
RUN echo "alias elam=$ELAM_ABSPATH/elam.sh" >> $HOME/.bash_aliases

RUN chmod +x \
  /scripts/create-env-example.sh \
  $HOME/.bashrc \
  $HOME/.inputrc

COPY scripts /scripts
