name: Push

on:
  push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    with:
      # Uses go version version
      image_tag: 1.24-ubuntu-test-27

      # https://hub.docker.com/repository/docker/utkusarioglu/ubuntu-devcontainer/tags
      base_tag: 2404-test-21
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    